--BD_MARTESDEPRUEBA.dbo.GRUPOANUAL 

ALTER TABLE BD_MARTESDEPRUEBA.dbo.GRUPOANUAL ADD IDColegioAnual int; 

ALTER TABLE BD_MARTESDEPRUEBA.dbo.GRUPOANUAL ADD Procesado bit not null CONSTRAINT [DF_GRUPOANUAL_Procesado]  DEFAULT (0); 

ALTER TABLE BD_MARTESDEPRUEBA.dbo.GRUPOANUAL ADD FechaProcesado DATETIME; 

ALTER TABLE BD_MARTESDEPRUEBA.dbo.GRUPOANUAL ADD ProcesadoSMART bit not null CONSTRAINT [DF_GRUPOANUAL_ProcesadoSMART]  DEFAULT (0); 

ALTER TABLE BD_MARTESDEPRUEBA.dbo.GRUPOANUAL ADD FechaProcesadoSMART DATETIME; 

ALTER TABLE BD_MARTESDEPRUEBA.dbo.GRUPOANUAL ADD MensajePasoHistorico VARCHAR(4000);